title: The Azure DevOps Blog
theme: minima
author: Manasi Belhe
email: manasi.belhe@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  The unoffical guide for DevOps, MLOps professionals using/plan to use Microsoft Azure as a Cloud Platform

# social links
github_username:  mabel91 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
